openapi: 3.0.1
info:
  title: API Componente A - Clientes y Pedidos
  version: 1.2.0
  description: API para gestión de clientes y pedidos con detalle de productos (MySQL)

servers:
  - url: http://localhost:8080

paths:
  /clientes:
    post:
      operationId: crearCliente
      summary: Crear un cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteInput'
      responses:
        '201':
          description: Cliente creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
    get:
      operationId: listarClientes
      summary: Listar todos los clientes
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'

  /clientes/{id}:
    get:
      operationId: obtenerClientePorId
      summary: Obtener un cliente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '404':
          description: Cliente no encontrado

  /pedidos:
    post:
      operationId: crearPedido
      summary: Crear un pedido con productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PedidoInput'
      responses:
        '201':
          description: Pedido creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pedido'
    get:
      operationId: listarPedidos
      summary: Listar todos los pedidos
      responses:
        '200':
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pedido'

  /pedidos/{id}:
    get:
      operationId: obtenerPedidoPorId
      summary: Obtener un pedido por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Pedido encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pedido'
        '404':
          description: Pedido no encontrado

  /pedidos/pendientes/{clienteId}:
    get:
      operationId: obtenerPedidosPendientesPorCliente
      summary: Obtener los pedidos pendientes de un cliente
      parameters:
        - name: clienteId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Lista de pedidos pendientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pedido'

components:
  schemas:
    Cliente:
      type: object
      properties:
        id: { type: integer, format: int32 }
        nombre: { type: string }
        correo: { type: string, format: email }

    ClienteInput:
      type: object
      required: [nombre, correo]
      properties:
        nombre: { type: string }
        correo: { type: string, format: email }

    Producto:
      type: object
      properties:
        nombre: { type: string }
        precio: { type: number, format: double }

    Pedido:
      type: object
      properties:
        id: { type: integer, format: int32 }
        clienteId: { type: integer, format: int32 }
        productos:
          type: array
          items:
            $ref: '#/components/schemas/Producto'
        total: { type: number, format: double }
        estado: { type: string, example: "PENDIENTE" }

    PedidoInput:
      type: object
      required: [clienteId, productos]
      properties:
        clienteId: { type: integer, format: int32 }
        productos:
          type: array
          items:
            $ref: '#/components/schemas/Producto'

